### ISSUE TITLE
Return value of VSwitch.ListBridges()

### ISSUE THREAD

**Issue by hwchiu** [digitalocean/go-openvswitch#53]
Hi all.

If there're not any OpenvSwitch in the system but the length of the return value of `VSwitch.ListBridges()` is 1 not zero.

I think that is caused by the `strings.Split` and you can find it below.
https://github.com/digitalocean/go-openvswitch/blob/56e8160f8f8dde705c86e3b720c63e627bad58fd/ovs/vswitch.go#L85-L93

Do we need to fix it by return a empty string array if the output of `list-br` is empty string?

Thanks.

**Comment by mdlayher** [comment]
Yep, that makes sense to me!

**Comment by chenyunchen** [comment]
Same here. Fix this #54 to return the empty array.

**Comment by hwchiu** [comment]
Has fixed, thanks
